// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SubstanciasAPI.Migrations
{
    [DbContext(typeof(SubstanciasDbContext))]
    partial class SubstanciasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Propriedades");
                });

            modelBuilder.Entity("Substancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Substancias");
                });

            modelBuilder.Entity("SubstanciaPropriedade", b =>
                {
                    b.Property<int>("SubstanciaId")
                        .HasColumnType("integer");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("integer");

                    b.Property<bool?>("ValorBool")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ValorDecimal")
                        .HasColumnType("numeric");

                    b.HasKey("SubstanciaId", "PropriedadeId");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("SubstanciaPropriedades");
                });

            modelBuilder.Entity("Substancia", b =>
                {
                    b.HasOne("Categoria", "Categoria")
                        .WithMany("Substancias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SubstanciaPropriedade", b =>
                {
                    b.HasOne("Propriedade", "Propriedade")
                        .WithMany("Substancias")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Substancia", "Substancia")
                        .WithMany("Propriedades")
                        .HasForeignKey("SubstanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");

                    b.Navigation("Substancia");
                });

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Navigation("Substancias");
                });

            modelBuilder.Entity("Propriedade", b =>
                {
                    b.Navigation("Substancias");
                });

            modelBuilder.Entity("Substancia", b =>
                {
                    b.Navigation("Propriedades");
                });
#pragma warning restore 612, 618
        }
    }
}
